"use client";

import { useEffect, useState } from "react";

type Task = { id: number; title: string; course: string; done: boolean };
const initialTasks: Task[] = [
  { id: 1, title: "Study Mathematics: Calculus Ch. 4", course: "MATH 201 · Due today", done: true },
  { id: 2, title: "Finish biology flashcards", course: "BIOLOGY · 20 min", done: true },
  { id: 3, title: "Read research paper notes", course: "PHYSICS · Deep work", done: false },
  { id: 4, title: "Draft history essay outline", course: "HISTORY · This week", done: false },
  { id: 5, title: "Review project milestones", course: "DESIGN · Tomorrow", done: false },
];

export default function Home() {
  const [tasks, setTasks] = useState(initialTasks);
  const [seconds, setSeconds] = useState(25 * 60);
  const [running, setRunning] = useState(false);
  const [sound, setSound] = useState(true);
  const [brightness, setBrightness] = useState(72);
  const [rain, setRain] = useState(35);
  const [toast, setToast] = useState("ADVANCEMENT MADE! Home Sweet Home");
  const [track, setTrack] = useState("Minecraft Volume Alpha · Subwoofer Lullaby");
  useEffect(() => { if (!running) return; const timer = window.setInterval(() => setSeconds(v => Math.max(0, v - 1)), 1000); return () => window.clearInterval(timer); }, [running]);
  const minutes = String(Math.floor(seconds / 60)).padStart(2, "0"); const secs = String(seconds % 60).padStart(2, "0");
  const done = tasks.filter(task => task.done).length;
  function announce(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2800); }
  function toggleTask(id: number) { setTasks(old => old.map(task => task.id === id ? { ...task, done: !task.done } : task)); }
  function addTask() { const id = Date.now(); setTasks(old => [...old, { id, title: "New focus quest", course: "UNTAGGED · Just added", done: false }]); announce("New quest added to your task list"); }
  return <main className="min-h-screen overflow-hidden bg-[#121312] text-stone-100"><video className="ambient" autoPlay muted loop playsInline src="/focus-room.mp4" /><div className="vignette" style={{ opacity: 1 - brightness / 100 }} /><div className="pixel-noise" />
    <header className="relative z-10 flex h-[88px] items-center justify-between border-b border-white/10 bg-[#14120f]/75 px-6 backdrop-blur-md lg:px-12"><div className="flex items-center gap-12"><div className="brand"><span className="brand-cube">◆</span> CRAFT<span>&amp;</span>FOCUS</div><nav className="hidden items-center gap-9 text-xs font-bold tracking-[.16em] text-stone-300 md:flex">{["STATS", "COMMUNITY", "HELP"].map(item => <button key={item} className="transition hover:text-amber-200">{item}</button>)}</nav></div><div className="flex items-center gap-4"><button onClick={() => { setSound(!sound); announce(sound ? "Interface sound muted" : "Interface sound enabled"); }} className="hud-icon" aria-label="Toggle sound">{sound ? "♬" : "♩̸"}</button><span className="hidden items-center gap-2 text-xs text-emerald-200 sm:flex"><i className="cloud-dot" /> Cloud saved</span><button onClick={() => announce("World progress synced to cloud")} className="sync-button">SYNC WORLD <span>↗</span></button></div></header>
    <div className="relative z-10 grid min-h-[calc(100vh-88px)] grid-cols-1 lg:grid-cols-[220px_minmax(560px,1fr)_400px]"><aside className="order-2 flex flex-col border-t border-white/10 bg-[#171511]/85 p-5 backdrop-blur-md lg:order-none lg:border-r lg:border-t-0 lg:p-7"><div className="profile-hud"><div className="steve-head"><span>■</span><span>■</span></div><div><p className="text-sm font-bold">Steve_Study</p><p className="mt-1 text-xs text-amber-200">LEVEL 42 <span className="text-stone-500">· 860 XP</span></p></div></div><nav className="mt-8 grid grid-cols-2 gap-2 lg:grid-cols-1">{[["◷", "TIMER"], ["▦", "INVENTORY"], ["✦", "ADVANCEMENTS"], ["⚙", "SETTINGS"]].map(([icon, item], index) => <button key={item} onClick={() => index && announce(`${item} opened`)} className={`side-link ${index === 0 ? "active" : ""}`}><span>{icon}</span>{item}</button>)}</nav><div className="mt-8 flex items-center justify-between lg:mt-auto"><button onClick={addTask} className="add-orb" aria-label="Add task">+</button><button onClick={() => announce("You have been safely logged out")} className="logout">⇥ LOGOUT</button></div></aside>
      <section className="relative flex min-w-0 flex-col items-center justify-center px-5 py-10 lg:px-10"><div className="absolute left-5 top-8 hidden items-center gap-3 lg:flex"><label className="ambient-control">☀<input aria-label="Daylight" type="range" min="25" max="100" value={brightness} onChange={e => setBrightness(Number(e.target.value))} /></label><label className="ambient-control">☂<input aria-label="Rain volume" type="range" min="0" max="100" value={rain} onChange={e => setRain(Number(e.target.value))} /></label></div><div className="advancement"><span>✦</span><div><b>ADVANCEMENT MADE!</b><p>Home Sweet Home</p></div><button onClick={() => setToast("")}>×</button></div><div className="timer-panel"><p className="focus-tag">FOCUS TIME</p><div className="timer-digits">{minutes}<span>:</span>{secs}</div><div className="stage-bars">{[0, 1, 2, 3].map(index => <i key={index} className={index === 0 ? "filled" : ""} />)}</div><p className="mt-3 text-xs uppercase tracking-[.24em] text-stone-400">Session 1 of 4</p><div className="mt-7 flex gap-3"><button className="timer-button secondary" onClick={() => { setSeconds(25 * 60); setRunning(false); }}>RESET</button><button className="timer-button primary" onClick={() => setRunning(!running)}>{running ? "PAUSE" : "START FOCUS"}</button></div></div><div className="music-player"><button onClick={() => setTrack("Minecraft Volume Alpha · Sweden")}>⏮</button><button className="play" onClick={() => setSound(!sound)}>{sound ? "Ⅱ" : "▶"}</button><button onClick={() => setTrack("Minecraft Volume Alpha · Wet Hands")}>⏭</button><div className="music-info"><span>NOW PLAYING</span><p>{track}</p></div></div></section>
      <aside className="space-y-6 border-t border-white/10 bg-[#171511]/85 p-6 backdrop-blur-md lg:border-l lg:border-t-0 lg:p-7"><section className="widget"><div className="widget-title"><div><p>CURRENT TASKS</p><span>{done}/{tasks.length} Done</span></div><button onClick={addTask}>+ ADD TASK</button></div><div className="task-list">{tasks.map(task => <label key={task.id} className={`task ${task.done ? "completed" : ""}`}><input type="checkbox" checked={task.done} onChange={() => toggleTask(task.id)} /><span className="checkmark">✓</span><span><b>{task.title}</b><small>{task.course}</small></span></label>)}</div></section><section className="book"><div className="book-ribbon">SESSION LOG · TODAY</div><h2>Dear adventurer,</h2><p>You mined through <b>75 focused minutes</b> today. Mathematics and biology are safely stored in your memory chest.</p><div className="book-line" /><p className="quote">“The secret of getting ahead is getting started.”</p><button onClick={() => announce("Your study result is ready to share")}>SHARE YOUR RESULT ↗</button></section></aside>
    </div>{toast && <div className="toast">{toast}</div>}</main>;
}
